users:
  luke:
    username: luke
    articleIds:
      - 1
    commentIds:
      - 1
  john:
    username: john
    articleIds:
      - 2
    commentIds:
      - 2
      - 3
articles:
  '1':
    id: 1
    title: >-
      read-yaml: Very thin wrapper around js-yaml for directly reading in YAML
      files.
    url: 'https://www.npmjs.com/package/read-yaml'
    username: luke
    commentIds:
      - 1
      - 2
    upvotedBy:
      - luke
    downvotedBy: []
    comments: []
  '2':
    id: 2
    title: >-
      write-yaml: Write YAML. Converts JSON to YAML writes it to the specified
      file.
    url: 'https://www.npmjs.com/package/write-yaml'
    username: john
    commentIds:
      - 3
    upvotedBy: []
    downvotedBy: []
    comments:
      - &ref_0
        id: 3
        body: 'Too easy mate, too easy!!!!!!!!1'
        username: john
        articleId: 2
        upvotedBy:
          - john
          - luke
        downvotedBy: []
nextArticleId: 3
comments:
  '1':
    id: 1
    body: This was useful!
    username: luke
    articleId: 1
    upvotedBy:
      - john
    downvotedBy: []
  '2':
    id: 2
    body: I agree!
    username: john
    articleId: 1
    upvotedBy: []
    downvotedBy: []
  '3': *ref_0
nextCommentId: 4
